micronaut:
  application:
    name: newsletter
---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
---
flyway:
  datasources:
    default:
      enabled: true
---
micronaut:
  security:
    filter:
      enabled: false
---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne #TODO Set this via environment variable
